- name: Ensure that the /etc/apt/keyrings dir exists
  file:
    path: /etc/apt/keyrings
    state: directory
    group: root
    owner: root
    mode: 0755

- name: Add Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc

- name: Add Docker repo
  vars:
    architecture_map:
      aarch64: arm64
      x86_64: amd64
  apt_repository:
    filename: docker
    repo: 'deb [arch={{ architecture_map[ansible_architecture] }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'

- name: Install Docker stuff
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Put dmitry in the docker group
  user:
    name: dmitry
    groups:
      - docker
    append: yes